id: P11E46543
initial_creation_type: ocr
source_metadata:
  volumes:
    dfe331f7902e402bbe20dd93b44beb0b:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
